env:
  - CGO_ENABLED=0
  - API_VERSION={{ if index .Env "API_VERSION"  }}{{ .Env.API_VERSION }}{{ else }}x5.0{{ end }}

before:
  hooks:
    - make

builds:
  -
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w'
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
    goos:
      - netbsd
      - solaris
      - openbsd
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: openbsd
        goarch: arm64
      - goos: darwin
        goarch: '386'

snapshot:
  name_template: "{{ if eq .Summary .Tag }}{{ .Version }}{{ else }}{{ incpatch .Version }}-dev{{ end }}"

# {{ incpatch .Version }}-dev-{{ .Tag }}

archives:
  - format: zip
    files:
      - none*
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - cmd: cosign
    env:
    - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true

changelog:
  use: github-native
